import { ColumnOptions, TaskList } from "../component/task/taskTypes";
import { getDaysBefore, getNextNWeekDay } from "./getWeekDays";

export const mockColumnOptions: ColumnOptions = {
  status: [
    { id: 1, title: "TO DO", color: "blue.300" },
    { id: 2, title: "IN PROGRESS", color: "purple.400", previousColumnId: 1 },
    { id: 3, title: "DONE", color: "green.400", previousColumnId: 2 },
  ],
  priority: [
    { id: 1, title: "NO PRIORITY", color: "gray.400" },
    { id: 2, title: "URGENT", color: "red.400" },
    { id: 3, title: "HIGH", color: "yellow.400" },
    { id: 4, title: "NORMAL", color: "blue.200" },
    { id: 5, title: "LOW", color: "gray.400" },
    { id: 0, title: "FINISHED", color: "null" },
  ],
  dueDate: [
    { id: 1, title: "NO DUE DATE", color: "gray.400" },
    { id: 2, title: "OVER DUE", color: "gray.400" },
    { id: 3, title: "MONDAY", color: "gray.400" },
    { id: 4, title: "TUESDAY", color: "gray.400" },
    { id: 5, title: "WEDNESDAY", color: "gray.400" },
    { id: 6, title: "THURSDAY", color: "gray.400" },
    { id: 7, title: "FRIDAY", color: "gray.400" },
    { id: 8, title: "SATURDAY", color: "gray.400" },
    { id: 9, title: "SUNDAY", color: "gray.400" },
    { id: 10, title: "FUTURE", color: "gray.400" },
    { id: 0, title: "FINISHED", color: "null" },
  ],
};

export const mockTaskList: TaskList = [
  {
    id: 111,
    title: "11111",
    status: 1,
    priority: 2,
    // dueDate: 1,
    expectedDueDate: undefined,
    previousTask: {},
    createdAt: getDaysBefore(11),
    taskEvents: [
      {
        id: 1,
        field: "comment",
        comment:
          "nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
        reactions: [],
        taskId: 111,
        userId: 3,
        username: "user",
        createdAt: getDaysBefore(10),
        updatedAt: getDaysBefore(3),
      },
      {
        id: 9,
        field: "comment",
        comment:
          "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
        reactions: [],
        taskId: 111,
        userId: 31,
        username: "user31",
        createdAt: getDaysBefore(10),
        updatedAt: getDaysBefore(3),
      },
      {
        id: 2,
        field: "title",
        beforeUpdate: "11112",
        afterUpdate: "11111",
        taskId: 111,
        userId: 3,
        username: "user",
        createdAt: getDaysBefore(9),
        updatedAt: getDaysBefore(1),
      },
      {
        id: 4,
        field: "status",
        beforeUpdate: "1",
        afterUpdate: "2",
        taskId: 111,
        userId: 2,
        username: "user2",
        createdAt: getDaysBefore(9),
        updatedAt: getDaysBefore(1),
      },
      {
        id: 3,
        field: "status",
        afterUpdate: "1",
        taskId: 111,
        userId: 3,
        username: "user",
        createdAt: getDaysBefore(9),
        updatedAt: getDaysBefore(1),
      },
      {
        id: 5,
        field: "priority",
        beforeUpdate: "2",
        afterUpdate: "3",
        taskId: 111,
        userId: 3,
        username: "user",
        createdAt: getDaysBefore(9),
        updatedAt: getDaysBefore(1),
      },
      {
        id: 6,
        field: "dueDate",
        beforeUpdate: "3",
        afterUpdate: "2",
        taskId: 111,
        userId: 3,
        username: "user",
        createdAt: getDaysBefore(9),
        updatedAt: getDaysBefore(1),
      },
      {
        id: 7,
        field: "assignee",
        taskId: 111,
        userId: 3,
        username: "user",
        createdAt: getDaysBefore(9),
        updatedAt: getDaysBefore(1),
        assignmentAction: "added",
        assignedUser: { userId: 3, username: "user" },
      },
      {
        id: 8,
        field: "watcher",
        taskId: 111,
        userId: 3,
        username: "user",
        createdAt: getDaysBefore(9),
        updatedAt: getDaysBefore(1),
        assignmentAction: "removed",
        assignedUser: { userId: 4, username: "abc" },
      },
    ],
    creatorId: 1,
    creatorName: "abc",
    watchers: [],
    assignees: [],
    previousTaskBeforeFinish: {},
  },
  {
    id: 222,
    title: "22222",
    status: 1,
    priority: 1,
    // dueDate: 1,
    expectedDueDate: undefined,
    previousTask: { statusId: 111, dueDateId: 111 },
    taskEvents: [],
    creatorId: 1,
    creatorName: "abc",
    watchers: [],
    assignees: [],
    previousTaskBeforeFinish: {},
  },
  {
    id: 333,
    title: "33333",
    status: 1,
    priority: 1,
    // dueDate: 1,
    expectedDueDate: undefined,
    previousTask: { statusId: 222, priorityId: 222, dueDateId: 222 },
    taskEvents: [],
    creatorId: 1,
    creatorName: "abc",
    watchers: [],
    assignees: [],
    previousTaskBeforeFinish: {},
  },
  {
    id: 444,
    title: "44444",
    status: 1,
    priority: 1,
    // dueDate: 2,
    expectedDueDate: getNextNWeekDay(-5),
    previousTask: { statusId: 333, priorityId: 333 },
    taskEvents: [],
    creatorId: 1,
    creatorName: "abc",
    watchers: [],
    assignees: [],
    previousTaskBeforeFinish: {},
  },
  {
    id: 555,
    title: "55555",
    status: 1,
    priority: 1,
    // dueDate: 2,
    expectedDueDate: getNextNWeekDay(-6),
    previousTask: { statusId: 444, priorityId: 444, dueDateId: 444 },
    taskEvents: [],
    creatorId: 1,
    creatorName: "abc",
    watchers: [],
    assignees: [],
    previousTaskBeforeFinish: {},
  },
  {
    id: 666,
    title: "66666",
    status: 1,
    priority: 3,
    // dueDate: 1,
    expectedDueDate: undefined,
    previousTask: { statusId: 555, priorityId: 777, dueDateId: 333 },
    taskEvents: [],
    creatorId: 1,
    creatorName: "abc",
    watchers: [],
    assignees: [],
    previousTaskBeforeFinish: {},
  },
  {
    id: 777,
    title: "77777",
    status: 1,
    priority: 3,
    // dueDate: 1,
    expectedDueDate: undefined,
    previousTask: { statusId: 666, dueDateId: 666 },
    taskEvents: [],
    creatorId: 1,
    creatorName: "abc",
    watchers: [],
    assignees: [],
    previousTaskBeforeFinish: {},
  },
];
