import {
  ColumnOptions,
  CurrentWeek,
  DueDateRange,
  Priority,
  TaskList,
} from "../types";
import { getDaysBefore, getNextNWeekDay } from "../utils/getWeekDays";

export const mockColumnOptions: ColumnOptions = {
  statusColumns: [
    { id: 1, title: "TO DO", color: "blue.300", orderIndex: 1 },
    { id: 3, title: "DONE", color: "green.400", orderIndex: 3 },
    { id: 2, title: "IN PROGRESS", color: "purple.400", orderIndex: 2 },
  ],
  priorityColumns: [
    { id: 1, title: Priority.NO_PRIORITY, color: "gray.400" },
    { id: 2, title: Priority.URGENT, color: "red.400" },
    { id: 3, title: Priority.HIGH, color: "yellow.400" },
    { id: 4, title: Priority.NORMAL, color: "blue.200" },
    { id: 5, title: Priority.LOW, color: "gray.400" },
  ],
  dueDateColumns: [
    { id: 1, title: DueDateRange.NO_DUE_DATE, color: "gray.400" },
    { id: 2, title: DueDateRange.OVER_DUE, color: "gray.400" },
    { id: 3, title: CurrentWeek.MONDAY, color: "gray.400" },
    { id: 4, title: CurrentWeek.TUESDAY, color: "gray.400" },
    { id: 5, title: CurrentWeek.WEDNESDAY, color: "gray.400" },
    { id: 6, title: CurrentWeek.THURSDAY, color: "gray.400" },
    { id: 7, title: CurrentWeek.FRIDAY, color: "gray.400" },
    { id: 8, title: CurrentWeek.SATURDAY, color: "gray.400" },
    { id: 9, title: CurrentWeek.SUNDAY, color: "gray.400" },
    { id: 10, title: DueDateRange.FUTURE, color: "gray.400" },
  ],
};

export const mockTaskList: TaskList = [
  {
    id: 111,
    creator: { userId: 1, username: "abc" },
    title: "11111",
    description: "desc here",
    expectedDueDate: undefined,
    createdAt: getDaysBefore(11),
    watchers: [],
    assignees: [],
    subTasks: [],
    taskEvents: [],
    status: { name: "TO DO", columnId: 1, orderIndex: 1 },
    priority: { name: Priority.HIGH, columnId: 3, orderIndex: 3 },
    dueDate: { name: DueDateRange.TODAY, columnId: 0, orderIndex: 1 },
  },
  {
    id: 222,
    title: "22222",
    creator: { userId: 1, username: "abc" },
    expectedDueDate: getNextNWeekDay(2),
    createdAt: getDaysBefore(4),
    watchers: [],
    assignees: [],
    taskEvents: [],
    subTasks: [],
    status: { name: "TO DO", columnId: 1, orderIndex: 2 },
    priority: { name: Priority.HIGH, columnId: 3, orderIndex: 2 },
    dueDate: { name: DueDateRange.TODAY, columnId: 0, orderIndex: 3 },
  },
  {
    id: 333,
    title: "33333",
    creator: { userId: 1, username: "abc" },
    expectedDueDate: new Date(),
    createdAt: getDaysBefore(4),
    watchers: [],
    assignees: [],
    taskEvents: [],
    subTasks: [],
    status: { name: "TO DO", columnId: 1, orderIndex: 3 },
    priority: { name: Priority.NO_PRIORITY, columnId: 1, orderIndex: 2 },
    dueDate: { name: DueDateRange.TODAY, columnId: 0, orderIndex: 2 },
  },
  {
    id: 444,
    title: "44444",
    creator: { userId: 1, username: "abc" },
    expectedDueDate: new Date(),
    createdAt: getDaysBefore(4),
    watchers: [],
    assignees: [],
    taskEvents: [],
    subTasks: [],
    status: { name: "TO DO", columnId: 1, orderIndex: 4 },
    priority: { name: Priority.NO_PRIORITY, columnId: 1, orderIndex: 4 },
    dueDate: { name: DueDateRange.TODAY, columnId: 0, orderIndex: 4 },
  },
  {
    id: 555,
    title: "55555",
    creator: { userId: 1, username: "abc" },
    expectedDueDate: new Date(),
    createdAt: getDaysBefore(4),
    watchers: [],
    assignees: [],
    taskEvents: [],
    subTasks: [],
    status: { name: "TO DO", columnId: 2, orderIndex: 5 },
    priority: { name: Priority.NO_PRIORITY, columnId: 1, orderIndex: 5 },
    dueDate: { name: DueDateRange.TODAY, columnId: 0, orderIndex: 5 },
  },
];
